name: k3s Testing
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: manticoresoftware/manticore-docker-test-kit:latest
          build-args: |
            DEV=1
            ARCH=amd
      - uses: manticoresoftware/clt@main
        with:
          image: manticoresoftware/manticore-docker-test-kit:latest
          test_prefix: clt_tests/
