name: Testing
on: push
concurrency:
  group: tests_${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build test kit
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: manticoresoftware/manticore-dind:latest
          context: ./clt_tests/dind/
      - uses: manticoresoftware/clt@0.6.5
        with:
          image: manticoresoftware/manticore-dind:latest
          test_prefix: clt_tests/tests/
          run_args: --privileged -v ".:/docker/"
